name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: npm install

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8


      - name: Install Cordova
        run: sudo npm install -g cordova --force

      - run: gradle init

      - run: export JAVA_HOME=$(/usr/libexec/java_home)

      - run: export PATH=$JAVA_HOME/bin:$PATH

      - run: echo $JAVA_HOME

      - run: gradle wrapper

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      # Run Build Project
      - name: Build gradle project
        run: ./gradlew build

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - run: export ANDROID_HOME=/Users/$(whoami)/Library/Android/sdk
      #- run: export ANDROID_HOME=/root/.android/sdk
      - run: export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools



      - name: Build SampleApplication
        run: ./gradlew --no-daemon build

      - name: Launch Script
        run: sudo npm run app far

      - name: Assemble Release Bundle
        run: |
          gradlew assembleRelease --stacktrace
