name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: npm install

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          cache: gradle

      - name: Install Cordova
        run: sudo npm install -g cordova --force

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Exportation de JAVA_HOME
        run: export JAVA_HOME=$(/usr/libexec/java_home)

      - name: Exportation de PATH
        run: export PATH=$JAVA_HOME/bin:$PATH

      - name: Exportation de ANDROID_HOME
        run: export ANDROID_HOME=/usr/local/lib/android/sdk

      - name: Exportation de PATH
        run: export PATH=$ANDROID_HOME/tools/bin:$PATH

      - name: Suppression du cache de Gradle
        run: rm -rf ~/.gradle/caches && ./gradlew --stop

      - name: Launch compilation APP
        run: sudo npm run app far
