name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: npm install

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: 17

      - name: Install Cordova
        run: sudo npm install -g cordova --force

      - run: gradle init

      - run: gradle wrapper

      - name: Change wrapper permissions
        run: chmod +x ./gradlew


      # Run Build Project
      - name: Build gradle project
        run: ./gradlew build

      - name: Launch Script
        run: sudo npm run app far

