name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          cache: gradle

      - name: Setup Gradle (Init)
        run: gradle init

      - name: Install Cordova
        run: sudo npm install -g cordova --force

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Exportation de JAVA_HOME
        run: export JAVA_HOME=$(/usr/libexec/java_home)

      - name: Exportation de ANDROID_SDK_ROOT
        run: export ANDROID_SDK_ROOT="/Users/$(whoami)/Library/Android/sdk/cmdline-tools/7.0/bin/sdkmanager platform-tools"

      - name: Suppression du cache de Gradle
        run: rm -rf ~/.gradle/caches


      - run: cordova create hello com.example.hello HelloWorld
      - run: cd hello && cordova platform add android && cordova prepare android && cordova build android

