name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - run: gradle init

      - run: gradle wrapper

      - name: Change wrapper permissions
        run: chmod +x ./gradlew


      # Run Build Project
      - name: Build gradle project
        run: ./gradlew build

        # Create APK Debug
      - name: Build apk debug project (APK) - ${{ env.main_project_module }} module
        run: ./gradlew assembleDebug

      # Create APK Release
      - name: Build apk release project (APK) - ${{ env.main_project_module }} module
        run: ./gradlew assemble

