name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: npm install

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Install Cordova
        run: sudo npm install -g cordova --force

      - run: gradle init

      - run: gradle wrapper

      - name: Change wrapper permissions
        run: chmod +x ./gradlew


      # Run Build Project
      - name: Build gradle project
        run: ./gradlew build

      - run: sudo chown -R 1001:123 "/root/.npm"

      - name: Launch Script
        run: sudo npm run app far

      # Create APK Release
      - name: Build apk release project (APK) - ${{ env.main_project_module }} module
        run: ./gradlew assemble

