name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use oxr463/setup-cordova
        uses: oxr463/setup-cordova@0.0.3
        with:
           exec: |
                              cordova platform add android && \
                              cordova build --no-telemetry && \
                              cp "$(find . -name '*.apk')" .
      - run: npm ci
      - run: npm run app far
