name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: npm install

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8



      - run: gradle init



      - run: gradle wrapper

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Liste des tasks
        run: gradle tasks --all



      # Run Build Project
      - name: Build gradle project
        run: ./gradlew build


      - name: Assemble Release Bundle
        run: |
          cd android && gradlew assembleRelease --stacktrace
