name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: gradle init
      - name: Build
        run: ./gradlew build
      - run: gradle wrapper
      - run: gradle projects
      - run: ./gradlew tasks --all
      - name: Set execution flag for gradlew
        run: chmod +x gradlew
      - name: Install npm dependencies
        run: |
          npm install
      - run: ls
      - name: Build Android Release
        run: |
          ./gradlew assembleRelease
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: app/build/outputs/apk/debug/app-debug.apk